name: myapp
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment: 
  sdk: '>= 3.0.0 <=3.3.4'

dependencies: 

  flutter: 
    sdk: flutter

  google_maps_flutter: ^2.5.0
  location: ^5.0.0
  flutter_polyline_points: ^2.0.0
  
  equatable: ^2.0.5
  speech_to_text: ^6.6.0
  firebase_core: ^2.16.0
  permission_handler: ^9.2.0
  bloc: ^8.1.2
  flutter_bloc: ^8.0.2

  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  intl: ^0.18.0
  shared_preferences: ^2.0.15
  provider: ^6.0.3
  json_annotation: ^4.6.0

  user_repository:
    path: packages/user_repository

  university_repository:
    path: packages/university_repository
  accordion: ^2.6.0
  flutter_animate: ^4.5.0
  firebase_crashlytics: ^3.5.4
  firebase_performance: ^0.9.4+4
  firebase_analytics: ^10.10.4
dev_dependencies:
  flutter_test: 
    sdk: flutter
  build_runner: ^2.2.1
  json_serializable: ^6.2.0

flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - assets/files/MOCK_DATA.json
  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsLight.ttf
          weight: 300
    - family: Quattrocento Sans
      fonts: 
        - asset: assets/fonts/QuattrocentoSans.ttf
          weight: 400
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoMedium.ttf
          weight: 500
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoRomanBold.ttf
          weight: 700
        - asset: assets/fonts/RobotoRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoBold.ttf
          weight: 700
        - asset: assets/fonts/RobotoLight.ttf
          weight: 300
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterMedium.ttf
          weight: 500